<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />

    <ProjectReference Include="..\LaquaiLib.Flux\LaquaiLib.Flux.csproj" />

    <Using Include="BenchmarkDotNet.Attributes" />
  </ItemGroup>

</Project>
