<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>$(NoWarn);CA2007</NoWarn>

    <RootNamespace>LaquaiLib.Flux</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />

    <Using Include="Xunit" />

    <ProjectReference Include="..\LaquaiLib.Flux\LaquaiLib.Flux.csproj" />
  </ItemGroup>

</Project>
