<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <RollForward>LatestMajor</RollForward>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>LaquaiLib.Flux</RootNamespace>

    <LangVersion>latest</LangVersion>
    <RollForward>LatestMajor</RollForward>
    <DebugType>portable</DebugType>
    <DebugSymbols>True</DebugSymbols>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">True</GeneratePackageOnBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>True</IncludeSymbols>
    <IsAotCompatible>true</IsAotCompatible>
    <Version>0.1.0</Version>

    <PackageId>$(AssemblyName)</PackageId>
    <PackageVersion>$(Version)</PackageVersion>
    <PackageDescription></PackageDescription>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/jolaquai/$(AssemblyName)</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
      <None Include="..\LICENSE;..\README.md" Pack="True" PackagePath="/" />

      <InternalsVisibleTo Include="$(AssemblyName).Benchmarks" />
      <InternalsVisibleTo Include="$(AssemblyName).Tests" />

      <Using Include="System.Buffers" />
      <Using Include="System.Diagnostics" />
      <Using Include="System.Diagnostics.Metrics" />
      <Using Include="System.Threading.Channels" />

      <Using Include="System.Runtime.CompilerServices" />
      <Using Include="System.Runtime.InteropServices" />

      <Using Include="System.Text" />

      <Using Condition="'$(TargetFramework)' == 'net9.0'"
             Include="System.Threading.Lock" Alias="LockType" />
      <Using Condition="'$(TargetFramework)' == 'net8.0'"
             Include="System.Object" Alias="LockType" />
  </ItemGroup>

</Project>
